
[[buffer]]
=== Buffer

Buffer objects are used in MoonNuklear only to store
draw commands and vertex data generated by _context:<<convert, convert>>(&nbsp;)_.

The memory area of a _buffer_ object may be either dynamically allocated ('_dynamic_') or 
of fixed size ('_fixed_'). In the former case, the buffer memory is managed
by Nuklear, while in the latter it must be provided and managed by the user.

[[new_buffer]]
* _buffer_ = *new_buffer*('_dynamic_') +
_buffer_ = *new_buffer*('_fixed_', [_ptr_, _size_]) +
[small]#The _ptr_ parameter, if passed, must be a lightuserdata containing a
valid pointer to _size_ bytes of contiguous memory. +
If _ptr_ and _size_ are not provided here, they must be provided later (before
using the buffer) by means of the _buffer:<<buffer.init, init>>(&nbsp;)_ method. +
Rfr: nk_buffer_init_default(&nbsp;), nk_buffer_init_fixed(&nbsp;).#

[[buffer.init]]
* _buffer_++:++*init*(_ptr_, _size_) +
[small]#Sets/modifies the _ptr_ and _size_ for '_fixed_' buffers (see _<<new_buffer, new_buffer>>(&nbsp;)_).#

[[buffer.ptr]]
* _ptr_ = _buffer_++:++*ptr*( ) +
[small]#Returns a lightuserdata containing the raw pointer (_void*_) to the buffer's memory.#

[[buffer.clear]]
* _buffer_++:++*clear*( ) +
*clear_buffers*(_buffer~1~_, _buffer~2~_, _..._) +
[small]#Clears the buffer (or a list of buffers), resetting its internal state.#

IMPORTANT: The buffers passed to _context:<<context.convert, convert>>(&nbsp;)_ must be
cleared at the end of each frame, since - starting from version 4.00.0 - Nuklear no longer
clears them automatically (see nuklear.h Changelog).

[[buffer.free]]
* _buffer_++:++*free*(_ptr_) +
[small]#Deletes the _buffer_ object and frees its memory, if the buffer is '_dynamic_'. +
(This method doesn't touch the _ptr_ of '_fixed_' buffers, i.e. any required free or unmap
of the memory pointed to by _ptr_ must be done by the user).#


