
[[convert]]
=== Convert

The <<context, _context_>> methods that follow are used in the backend to
control the conversion of vertex data and draw commands from the formats used
internally by Nuklear to formats accessible by the particular system API in use.

See the https://cdn.statically.io/gh/Immediate-Mode-UI/nuklear/master/doc/nuklear.html#nuklear/api/drawing[Drawing] section in the Nuklear documentation for more details.

[[context.convert]]
* <<convertresultflags, _convertresultflags_>> = _context_$$:$$*convert*(<<buffer, _cbuffer_>>, <<buffer, _vbuffer_>>, <<buffer, _ebuffer_>>) +
[small]#Converts the data generated by the frontend drawings and stores the abstract
draw commands in the given _cbuffer_, the vertex data in _vbuffer_, and the element
indices data in _ebuffer_.
The conversion is done according to the current 'convert configuration' for the _context_, that 
can be set with the _context_$$:$$<<convert_config, config_xxxx>>(&nbsp;) methods. +
Rfr: nk_convert(&nbsp;).#

[[context.commands]]
* {<<command, _command_>>} = _context_$$:$$*commands*( ) +
{<<drawcommand, _drawcommand_>>} = _context_$$:$$*draw_commands*(<<buffer, _cbuffer_>>) +
[small]#These methods return the list of commands generated by _context_$$:$$<<context.convert, convert>>(&nbsp;). The backend is expected to translate these commands to system API calls and render them. +
Rfr: nk_foreach(&nbsp;), nk_draw_foreach(&nbsp;).#

[[clear]]
* _context_$$:$$*clear*( ) +
[small]#Clears the _context_'s state. This method must be called at the end of each frame,
after the converted commands have been rendered. +
(Also remember to <<buffer.clear, clear>> the buffers passed to 
_context_$$:$$<<context.convert, convert>>(&nbsp;)). +
Rfr: nk_clear(&nbsp;).#

[[convert_config]]
* _context_$$:$$*config_reset*( ) +
_context_$$:$$*config_global_alpha*(_float_) +
_context_$$:$$*config_line_aa*(_boolean_) +
_context_$$:$$*config_shape_aa*(_boolean_) +
_context_$$:$$*config_circle_segment_count*(_integer_) +
_context_$$:$$*config_arc_segment_count*(_integer_) +
_context_$$:$$*config_curve_segment_count*(_integer_) +
_context_$$:$$*config_null_texture*(_texid_, <<vec2, _uv_>>) +
_context_$$:$$*config_vertex_layout*({<<drawvertexlayoutelement, _drawvertexlayoutelement_>>}) +
_context_$$:$$*config_vertex_size*(_integer_) +
_context_$$:$$*config_vertex_alignment*(_integer_) +
[small]#Set the conversion parameters associated with the _context_. +
Rfr: nk_convert_config_t struct.#

