
[[convert]]
=== Convert

See the https://rawgit.com/vurtun/nuklear/master/doc/nuklear.html#toc1.7.3[Drawing]
section in the Nuklear documentation.

The <<context, _context_>> methods that follow are to be used in the backend renderer to
configure and perform the conversion of vertex data and draw commands from the Nuklear
internal formats to formats accessible by the particular system API in use.

[[convert_config]]
* _context_++:++*config_reset*( ) +
_context_++:++*config_global_alpha*(_float_) +
_context_++:++*config_line_aa*(_boolean_) +
_context_++:++*config_shape_aa*(_boolean_) +
_context_++:++*config_circle_segment_count*(_integer_) +
_context_++:++*config_arc_segment_count*(_integer_) +
_context_++:++*config_curve_segment_count*(_integer_) +
_context_++:++*config_null_texture*(_texid_, <<vec2, _uv_>>) +
_context_++:++*config_vertex_layout*({<<drawvertexlayoutelement, _drawvertexlayoutelement_>>}) +
_context_++:++*config_vertex_size*(_integer_) +
_context_++:++*config_vertex_alignment*(_integer_) +
[small]#Set the convert configuration associated with the _context_. +
Rfr: nk_convert_config_t.#

[[context.convert]]
* <<convertresultflags, _convertresultflags_>> = _context_++:++*convert*(<<buffer, _cbuffer_>>, <<buffer, _vbuffer_>>, <<buffer, _ebuffer_>>) +
[small]#Convert the data generated by the front-end drawings. +
Stores the abstract draw commands in the given _cbuffer_, the vertex data in _vbuffer_, and the element indices data in _ebuffer_. +
The conversion is done according to the current 'convert configuration' for the _context_, that 
can be set with the _context:<<convert_config, config_xxxx>>(&nbsp;)_ methods. +
Rfr: nk_convert(&nbsp;).#

[[context.commands]]
* {<<command, _command_>>} = _context_++:++*commands*( ) +
{<<drawcommand, _drawcommand_>>} = _context_++:++*draw_commands*(<<buffer, _cbuffer_>>) +
[small]#These methods return the list of commands generated by _context:<<context.convert, convert>>(&nbsp;)_. The backend is expected to translate these commands to system API calls and render them. +
Rfr: nk_foreach(&nbsp;), nk_draw_foreach(&nbsp;).#

[[clear]]
* _context_++:++*clear*( ) +
[small]#Clears the _context_'s state. This method must be called at the end of each frame,
after the converted commands have been rendered. +
(Also remember to <<buffer.clear, clear>> the buffers passed to 
_context:<<context.convert, convert>>(&nbsp;)_). +
Rfr: nk_clear(&nbsp;).#

