

[[input_mirroring]]
=== Input mirroring

Updated input information must be provided to Nuklear at each frame, using the
<<input_xxx, input_xxx>>(&nbsp;) functions in a code section delimited by 
<<input_begin, input_begin>>(&nbsp;) and <<input_end, input_end>>(&nbsp;).
See also the https://immediate-mode-ui.github.io/Nuklear/doc/index.html#nuklear/api/input[Input] section in the Nuklear documentation.

[[input_begin]]
* *input_begin*(_context_) +
*input_end*(_context_) +
[small]#Rfr: nk_input_begin(&nbsp;), nk_input_end(&nbsp;).#

[[input_xxx]]
* *input_key*(_context_, <<keys, _key_>>, _down_) +
*input_button*(_context_, <<buttons, _button_>>, _x_, _y_, _down_) +
*input_scroll*(_context_, _x_, _y_) +
*input_motion*(_context_, _x_, _y_) +
*input_mouse_pos*(_context_, _x_, _y_) [small]#- _Note1_# +
*input_char*(_context_, _char_) +
*input_glyph*(_context_, _glyph_) +
*input_unicode*(_context_, _codepoint_) +
[small]#Note1: unlike _input_motion(&nbsp;)_, _input_mouse_pos(&nbsp;)_ only sets the mouse 
position without updating delta and prev (used e.g. in mouse grabbing). +
Rfr: nk_input_xxx(&nbsp;).#

[[input_keys]]
* *input_keys*(_context_, <<keytable, _keytable_>>) +
[small]#This function can be used to mirror all the keys with a single call.
Any missing field in the <<keytable, _keytable_>> defaults to _false_ (i.e. key up).#

[[input_queries]]
=== Input queries

The following <<context, _context_>> methods can be used (usually by the frontend)
to query mirrored input information relevant to the GUI.

* _boolean_ = _context_++:++*is_mouse_down*(<<buttons,_button_>>) +
_boolean_ = _context_++:++*is_mouse_pressed*(<<buttons,_button_>>) +
_boolean_ = _context_++:++*is_mouse_released*(<<buttons,_button_>>) +
_boolean_ = _context_++:++*mouse_clicked*(<<buttons,_button_>>, <<rect, _rect_>>) +
_boolean_ = _context_++:++*has_mouse_click*(<<buttons,_button_>>) +
_boolean_ = _context_++:++*has_mouse_click_in_rect*(<<buttons,_button_>>, <<rect, _rect_>>) +
_boolean_ = _context_++:++*has_mouse_click_in_button_rect*(<<buttons,_button_>>, <<rect, _rect_>>) +
_boolean_ = _context_++:++*has_mouse_click_down_in_rect*(<<buttons,_button_>>, <<rect, _rect_>>, _down_) +
_boolean_ = _context_++:++*is_mouse_click_in_rect*(<<buttons,_button_>>, <<rect, _rect_>>) +
_boolean_ = _context_++:++*is_mouse_click_down_in_rect*(<<buttons,_button_>>, <<rect, _rect_>>, _down_) +
_boolean_ = _context_++:++*any_mouse_click_in_rect*(<<rect, _rect_>>) +
_boolean_ = _context_++:++*is_mouse_prev_hovering_rect*(<<rect, _rect_>>) +
_boolean_ = _context_++:++*is_mouse_hovering_rect*(<<rect, _rect_>>) +
_x_, _y_ = _context_++:++*mouse_pos*( ) +
_x_, _y_ = _context_++:++*mouse_prev*( ) +
_dx_, _dy_ = _context_++:++*mouse_delta*( ) +
_dx_, _dy_ = _context_++:++*mouse_scroll_delta*( ) +
_boolean_ = _context_++:++*mouse_grabbed*( ) +
_boolean_ = _context_++:++*mouse_grab*( ) +
_boolean_ = _context_++:++*mouse_ungrab*( ) +
_boolean_ = _context_++:++*is_key_pressed*(<<keys, _key_>>) +
_boolean_ = _context_++:++*is_key_released*(<<keys, _key_>>) +
_boolean_ = _context_++:++*is_key_down*(<<keys, _key_>>) +
[small]#Rfr: nk_input_xxx(&nbsp;), nk_input.#

