
== Overview

A (Moon)Nuklear application is a GUI application having two main components:
footnote:[Of course an application may have many other important components.
We are considering here only those related to GUI drawing via Nuklear.]

* a *frontend*, whose task is to define ('draw') the GUI independently of the system API, and
* a *backend*, whose task is to interface Nuklear to the system API.

By *system API* we mean here the set of APIs through which we access the window system,
handle input, render pixels on the screen, and so on (e.g. GLFW+OpenGL, GLUT+OpenGL, GLFW+Vulkan, ...).

To create a GUI, the application must first create a <<context, *context*>>, which is
an object that mantains minimal state for the application and links together
the frontend and the backend.
The application creates a context by calling the <<init, init>>(&nbsp;) function, optionally
passing it a <<font, *font*>> to be used for text rendering
footnote:[A font for text rendering must eventually be provided, but this can be
done either by passing it to <<init, init>>(&nbsp;) as well as later
during the initialization phase.]. 

Then, after having performed any other initialization such as those required by
the system API, the application enters its main *event loop* where (ideally) at each iteration it
reacts to input events and ends up rendering a frame on the screen. 
Omitting the details, each iteration of the event loop consists of the following steps:

1. The _backend_ <<input_mirroring, mirrors the input>>, i.e. it collects input information
via the system API and relays such information to Nuklear.
2. The _frontend_ draws the GUI using Nuklear's frontend API (<<window, window>>,
<<layout, layout>>, <<widgets, widgets>>, etc),
possibly <<input_queries, accessing input information>> via context methods and modifying
the aspect of the GUI accordingly.
Upon each call of its frontend API, Nuklear generates vertex data and abstract draw commands
('abstract' in the sense that they do not depend on any particular system API).
3. The _backend_ <<convert, converts>> the vertex data to the format expected by the system API,
possibly uploads it to the rendering device (e.g. the GPU), retrieves the list of abstract
draw commands generated by Nuklear, and eventually *renders* the frame, by mapping the
abstract draw commands to concrete system API calls (e.g. OpenGL draw commands).

Notice how the frontend is in charge only of drawing the GUI, which it does
independently and without any knowledge of the system API being used to concretely draw it.
This means that once a frontend is developed, it should be reusable without changes with
different backends, i.e. with different system APIs or even on different systems.

Also notice that the frontend must redraw the GUI at every frame: nothing about the GUI itself
(its layout, which widgets it contains, their state, etc.) is retained across frames 
by Nuklear nor by the GPU.
This is what https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics)['immediate mode'] means.
footnote:[The biggest price to pay for this (at least in GPU rendering) is that vertex data
must be uploaded to the GPU at every frame. While this may be prohibitive when rendering
complex graphics scenes, it is usually acceptable for simple GUIs like those for which
Nuklear is intended for.]

This also means that a backend for a particular system API is a fairly general piece of
code that can be reused for different frontends, thus one need not rewrite a new one
every time he/she writes an application. Moreover, the backend is not required to do any
fancy or particularly complex graphics task: it is only required to mirror input information
from the system API to Nuklear, and to draw concretely the vertices that Nuklear asks it to
draw via its abstract commands (Nuklear takes care to pass to the backend vertex data that
will result in the GUI as intended by the frontend, and the backend blindly draws it).

A GLFW+OpenGL backend is provided with MoonNuklear (*moonnuklear/glbackend.lua*).
This backend is used in the examples and requires https://github.com/stetre/moongl[MoonGL] and
https://github.com/stetre/moonglfw[MoonGLFW].

The rest of this manual lists the MoonNuklear Lua bindings to the functions provided by Nuklear for 
the above operations. A few examples can be found in the *examples/* directory of the repository,
mostly portings to Lua of the original examples that come with Nuklear (including the comprehensive demo).

